allowBuilds:
  '@nestjs/core': false
  '@swc/core': true
  lefthook: true
  msw: true

minimumReleaseAge: 4320

patchedDependencies:
  nest-commander: patches/nest-commander.patch

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3 # https://github.com/paulmillr/chokidar/issues/1440
