ignoredBuiltDependencies:
  # Runs opencollective funding prompt on postinstall
  - '@nestjs/core'

# 3 days in minutes
minimumReleaseAge: 4320

onlyBuiltDependencies:
  # Downloads platform-specific native binary for TypeScript/JavaScript compilation
  - '@swc/core'
  # Downloads platform-specific native binary for bundling/minification
  - esbuild
  # Downloads platform-specific binary and runs 'lefthook install' to set up git hooks
  - lefthook

patchedDependencies:
  nest-commander: patches/nest-commander.patch

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  # https://github.com/paulmillr/chokidar/issues/1440
  - chokidar@4.0.3
